CREATE TABLE EMPLOYEE (
    ID             VARCHAR(20),
    NAME           VARCHAR(100) NOT NULL,
    DOJ            DATE         NOT NULL,
    DESIGNATION    VARCHAR(30)  NOT NULL,
    EMAIL          VARCHAR(50)  NOT NULL,
    CONTACT_NUMBER VARCHAR(30)  NOT NULL,
    GENDER         VARCHAR(6)   NOT NULL,
    PRIMARY KEY (ID)
)
    ENGINE = InnoDB
    DEFAULT CHARSET = latin1;

CREATE TABLE EMPLOYEE (
    ID             VARCHAR(20),
    NAME           VARCHAR(100) NOT NULL,
    DOJ            DATE         NOT NULL,
    DESIGNATION    VARCHAR(30)  NOT NULL,
    EMAIL          VARCHAR(50)  NOT NULL,
    CONTACT_NUMBER VARCHAR(30)  NOT NULL,
    GENDER         VARCHAR(6)   NOT NULL,
    PRIMARY KEY (ID)
)
    ENGINE = InnoDB
    DEFAULT CHARSET = latin1;